### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by trohnjavolta** [jaymoulin/docker-rpi-jdownloader#19]
**Description**

I run the docker an Odroid HC2, Armboard, Os Armbian (debian stretch flavor).
After starting the container jd2 seems to update just fine, but the container log shows following error:
My.jdownloader also seems no running instance.

```
24|Log.L.log 11/18/18 3:08:38 PM - SEVERE [ Log.L.log ] -> Exception thrown at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:935):
java.lang.ExceptionInInitializerError
	at jd.SecondLevelLaunch$10$1.run(SecondLevelLaunch.java:786)

	Caused by: java.lang.RuntimeException: No Console Available!
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:54)
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:60)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:118)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:107)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:32)
```

**Command line I used to start the container**
Same as is provided in readme.
**Steps to reproduce the issue:**
1.Start/restart container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Provide some logs (`docker logs jdownloader`)**
[jd.log](https://github.com/jaymoulin/docker-jdownloader/files/2592891/jd.log)

**Output of `docker inspect jdownloader --format='{{index .Config.Labels.version}}'`:**
0.6.0

**Comment by jaymoulin** [comment]
You can also mount your `cfg` folder to a volume

Feel free to donate, star Github rpo and Docker image to help me making great products :)
